development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: project1_db
  pool: 5
  username: root
  password: root123
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: project1_db
  pool: 5
  username: root
  password: root123
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: project1_db
  pool: 5
  username: root
  password: root123
  host: localhost